# Generated by Django 2.2 on 2021-03-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_address',
            new_name='email',
        ),
    ]
